const principal = {
    id: "123",
    email: "rinorhajrizi1718@gmail.com",
    firstName: "Rinor",
    lastName: "Hajrizi",
    birthdate: new Date(1999, 1, 31),
    livingIn: "Prishtina",
    education: "UBT",
    workingAt: "Celonis",
    hobby: "table-tennis",
};

const posts = [
    {
        id: "1",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "This is my first #social network post!",
        likes: 23,
    },
    {
        id: "2",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "Being in social net is so fun! I can become friends with many people of similar interests and spend my time #reading interesting posts",
        likes: 27,
    },
    {
        id: "3",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "I like social net's design. It is very easy and intiutive to use.",
        likes: 29,
    },
    {
        id: "4",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "This is my first #social network post!",
        likes: 63,
    },
    {
        id: "5",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "Being in social net is so fun! I can become friends with many people of similar interests and spend my time #reading interesting posts",
        likes: 98,
    },
    {
        id: "6",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "This is my last #social network post!",
        likes: 231,
    },
    {
        id: "7",
        postedBy: principal,
        dateAndTimePosted: new Date(2018, 4, 2),
        content: "I like social net's design. It is very easy and intiutive to use.",
        likes: 98,
    },
];

const friends = [
    {
        id: "1",
        firstName: "Veton",
        lastName: "Hajrizi",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "2",
        firstName: "Jon",
        lastName: "Hajrizi",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "3",
        firstName: "Ermal",
        lastName: "Hajrizi",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "4",
        firstName: "Ilmi",
        lastName: "Hajdini",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "5",
        firstName: "John",
        lastName: "Doe",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "6",
        firstName: "Name",
        lastName: "Surname",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "7",
        firstName: "First",
        lastName: "Second",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "8",
        firstName: "Random",
        lastName: "Person",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "9",
        firstName: "Leo",
        lastName: "Messi",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "10",
        firstName: "James",
        lastName: "Smith",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "11",
        firstName: "Pellumb",
        lastName: "Hajdari",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "19",
        firstName: "Leo",
        lastName: "Messi",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "13",
        firstName: "James",
        lastName: "Smith",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
    {
        id: "14",
        firstName: "Pellumb",
        lastName: "Hajdari",
        birthdate: new Date(1998, 3, 15),
        education: "UBT",
        workingAt: "Celonis",
        hobby: "table-tennis",
    },
];

const activities = [
    {
        id: "1",
        commitedBy: principal,
        actionType: "LIKE",
        targetUser: friends[0],
        targetPost: posts[0],
    },
    {
        id: "21",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[0],
        targetPost: null,
    },
    {
        id: "12",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[1],
        targetPost: null,
    },
    {
        id: "23",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[2],
        targetPost: null,
    },
    {
        id: "14",
        commitedBy: principal,
        actionType: "LIKE",
        targetUser: friends[1],
        targetPost: posts[1],
    },
    {
        id: "25",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[3],
        targetPost: null,
    },
    {
        id: "16",
        commitedBy: principal,
        actionType: "LIKE",
        targetUser: friends[3],
        targetPost: posts[4],
    },
    {
        id: "26",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[0],
        targetPost: null,
    },
    {
        id: "17",
        commitedBy: principal,
        actionType: "LIKE",
        targetUser: friends[3],
        targetPost: posts[4],
    },
    {
        id: "28",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[0],
        targetPost: null,
    },
    {
        id: "18",
        commitedBy: principal,
        actionType: "LIKE",
        targetUser: friends[3],
        targetPost: posts[4],
    },
    {
        id: "29",
        commitedBy: principal,
        actionType: "FRIENDSHIP",
        targetUser: friends[3],
        targetPost: posts[4],
    },
];

export default { principal, posts, friends, activities };